theme: jekyll-theme-slate
title: Cookbook Politics
subtitle: Reading and Writing U.S. Culinary History
description: Homepage for Fall 2021 Student Opportunities in Undergraduate Learning (SOUL) course
author: Elena Palazzolo
